# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0003_auto_20200226_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighbor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoods.Neighborhood'),
        ),
    ]
